### PR TITLE
User enter a session, he has not created. _userLogged is not yet assi…

### PR DESCRIPTION
**Pull request by corinnekrych**
…gned
@edewit when a user joins a session, there was a null pointer exception because _userLogged was not yet assigned

### CODE REVIEW

**Comment by edewit** [comment]
Can you elaborate on how to reproduce this? Cause the user is created on the fist page and always passed to the other pages it cannot be null

**Comment by corinnekrych** [comment]
@edewit Here is how i reproduce it
- user enter his name
- user jouns a room
- the detailled session is displayed, xaml page goes to IsAdmin before navigatedfrom async is executed (where you set userlogged), therefore null exception
  Do youreproduce it?

**Comment by edewit** [comment]
Have tried a thousand times now but for me `OnNavigatedToAsync` is executed before `IsAdmin` all of the time

**Comment by corinnekrych** [comment]
@edewit and for me it fails consistently when i join a session without having created it :/
I guess it's an one of those async issue that depends on how quick stuff happens 
I think checking for null does not harm the flow.... let me review it with @secondsun tonight

**Comment by corinnekrych** [comment]
@edewit maybe we should set userlogged sooner?

**Comment by edewit** [comment]
The idea of `OnNavigatedTo` is that it happens before seeing the page, let's add the null check but like this:

``` csharp
public bool IsAdmin => _loggedUser?.Name.Equals(SelectedSession.CreatedBy.Name) ?? false;
```

Cause then it's a nice one liner 😄 , does it still work for you with this check?

**Comment by edewit** [comment]
added it to https://github.com/edewit/PointingHenry10/commit/193ed26d0b500149d1726951b4d46c2a073cb011 in the showVote branch

**Pull request closed without merging**
